export{default as Header} from "./Header/Header"
export{default as Container} from "./Container/Container"
export{default as Footer} from "./Footer/Footer"
export {default as Section} from "./Section/Section"
export {default as HomeMain} from "./HomeMain/HomeMain"
export {default as Services} from "./Services/Services"
export {default as Card} from "./Card/Card"
export {default as SectionTitle} from "./SectionTitle/SectionTitle"
export {default as Technologies} from "./Technologies/Technologies"
export {default as Projects } from "./Projects/Projects"
export {default as CardProjects } from "./CardProjects/CardProjects"
export {default as SliderProject } from "./SliderProject/SliderProject"
export {default as Backdrop } from "./Backdrop/Backdrop"
export {default as Cont } from "./Cont/Cont"
export {default as Info } from "./Info/Info"
export {default as Formulaire } from "./Formulaire/Formulaire"
export {default as ContAbout } from "./ContAbout/ContAbout"

